const express = require("express");
const http = require("http");
const { Server } = require("socket.io");

const app = express();
const server = http.createServer(app);
const io = new Server(server);

app.use(express.static("public"));

const rooms = {
    "Left": { 
        "password": "Left1515", 
        "users": [], 
        "turnIndex": 0,
        "assets": {
            "left": "/Images/Allison.jpg",
            "right": "/Images/Pranav_app.jpg"
        }
    },
    "Right": { 
        "password": "Right2727", 
        "users": [], 
        "turnIndex": 0,
        "assets": {
            "left": "/Images/sam.jpg",
            "right": "/Images/Breanna.jpg"
        }
    }
};

const questionBank = {
    "Deep": [
        "What is a core memory from your childhood that you think shaped who you are today?",
        "If you could change one thing about how you were raised, what would it be?",
        "What is a fear you have that you rarely admit out loud to anyone?",
        "When was the last time you felt truly lonely, even if people were around you?",
        "What does success look like to you at this stage in your life?",
        "Do you believe people can genuinely change, or do they just get better at hiding things?",
        "What is a belief you held firmly five years ago that you completely disagree with now?",
        "If you died tomorrow, what would be your biggest regret about what you left unsaid or undone?",
        "What is something you are currently struggling with internally that I might not notice?",
        "How do you typically handle emotional pain—do you process it, distract yourself, or bury it?",
        "What is the hardest lesson you’ve ever had to learn the hard way?",
        "Do you think you are more like your mother or your father, and how do you feel about that?",
        "What is something you’re proud of that you don’t usually brag about?",
        "What does forgiveness mean to you? Is there anyone you haven't forgiven?",
        "If a crystal ball could tell you the truth about your future, what would you want to know?",
        "What is your absolute favorite quality about yourself?",
        "What is something you find yourself constantly worrying about, even though it’s out of your control?",
        "How do you think your younger self would view the person you are today?",
        "What is a boundary you’ve set recently that was really hard for you to enforce?",
        "What gives your life the ultimate sense of meaning or purpose?",
        "What is an assumption people frequently make about you that is totally wrong?",
        "If you could heal one past emotional wound instantly, which one would it be?",
        "What does home mean to you—is it a place, a person, or a state of mind?",
        "What is a dream you’ve given up on, and do you regret letting it go?",
        "How do you want to be remembered by the people closest to you when you’re gone?",
        "Piece of advice you received that completely changed the trajectory of your life?",
        "When you are in a bad mood, do you prefer space to process or do you want to be distracted?",
        "What is the most emotionally exhausting thing about your day-to-day routine right now?",
        "Do you think you judge yourself more harshly than you judge other people, or vice versa?",
        "What is something you had to let go of in the past year that was incredibly painful but necessary?",
        "If you could ask a single question to an omniscient being and get a completely honest answer, what would you ask?",
        "What does financial security mean to you emotionally? Does it represent freedom, safety, or status?",
        "What is a personal rule or boundary you have set for yourself that you will never break?",
        "When was the last time you cried, and what was the underlying reason behind those tears?",
        "Do you think people are inherently good, inherently selfish, or just products of their environment?",
        "What is an area of your life where you feel like you are currently settling or compromising too much?",
        "How do you handle criticism? Does it make you defensive, or do you internalize it deeply?",
        "What is a trait you see in other people that instantly makes you lose respect for them?",
        "If you could go back and talk to yourself on the first day of high school, what would you say?",
        "What is something you’re currently trying to forgive yourself for?",
        "Do you find it easy or difficult to ask for help when you are drowning in tasks or emotions?",
        "What is a major life goal you used to have that you realized you no longer care about at all?",
        "What is the closest you have ever felt to a spiritual or transcendent experience?",
        "How do you typically react when a plan you were incredibly excited about falls through at the last minute?",
        "What is an aspect of your personality that you actively try to hide or tone down around new people?",
        "If you could instantly acquire one character trait or emotional skill that you lack, what would it be?",
        "What does peace of mind look like to you in a practical, everyday sense?",
        "What is a memory you have that always makes you feel instantly angry or frustrated when it pops up?",
        "Do you feel like you are living your life for yourself right now, or are you living it to fulfill others' expectations?",
        "What is the most profound realization you’ve ever had about yourself during a period of solitude?",
        "What is an insecurity you had as a teenager that you completely outgrew, and how did you do it?",
        "Do you think it is more important to be respected by your peers, loved by your family, or satisfied with yourself?",
        "What is a piece of art, a book, or a movie that fundamentally shifted the way you view human nature?",
        "How do you handle feelings of jealousy or envy when you see someone else achieving what you want?",
        "What is something you think you are currently taking for granted in your life right now?",
        "If you could undo one decision you made in the last three years, which one would it be and why?",
        "What does the concept of aging mean to you? Does it scare you, or do you look forward to it?",
        "When was the last time you felt like an absolute impostor, and how did you push through that feeling?",
        "What is a truth about yourself that you try very hard to avoid thinking about?",
        "Do you think your current career path or daily routine aligns with what you genuinely value in life?",
        "What is the most significant sacrifice you have ever made for another person, and do you regret it?",
        "How do you find closure when a situation or a relationship ends without a proper explanation?",
        "What is a specific compliment or piece of validation you received that made you feel truly seen as a person?",
        "Do you struggle more with letting go of the past or worrying about what’s going to happen in the future?",
        "What is a habit or defense mechanism you have that you know is toxic but find incredibly hard to break?",
        "If you had to describe your current emotional state as a weather pattern, what does it look like right now?",
        "What is a lesson about love or relationships that you had to unlearn because it was holding you back?",
        "When you look at the world today, what gives you the most genuine sense of hope for the future?",
        "What is something you used to find incredibly embarrassing that you now find completely normal or even endearing?",
        "How do you define a life well-lived? What are the non-negotiable metrics for you?",
        "What is a secret burden or responsibility you carry that you rarely talk to anyone about?",
        "Do you think you are fundamentally a private person, or do you crave deep vulnerability with multiple people?",
        "What is a personal failure that you are now deeply grateful happened because of where it led you?",
        "If you could instantly master any emotional discipline (like patience, stoicism, or radical empathy), which one would you choose?",
        "What is the most beautiful thing you have ever witnessed another human being do for someone else?",
        "What is a piece of advice you gave someone else that you desperately wish you could take yourself?",
        "What is a reassurance you find yourself needing from me more often lately?",
        "When do you feel the most self-conscious around me, and what can I do to make you feel more at ease?",
        "What is a boundary you have been hesitating to set with me because you are afraid of how I might react?",
        "What is an opinion or perspective you hold that you usually keep quiet about because you don't want to argue?",
        "When was the last time you felt a little bit unappreciated by me, even if it was just for a fleeting moment?",
        "What is a current insecurity of yours that has absolutely nothing to do with your physical appearance?",
        "When we are having a disagreement, what is the exact moment or phrase that makes your walls instantly go up?",
        "What is a small mistake you made recently that you felt strangely guilty or embarrassed about?",
        "What part of your current weekly routine makes you feel the most lonely or isolated?",
        "What is something you’ve been procrastinating on because you’re secretly terrified you won't do it perfectly?",
        "What is a social situation that completely drains your energy, and how do you typically mask it around others?",
        "What is a piece of feedback or criticism I gave you in the past that secretly stung, even if you didn't show it at the time?",
        "What is something you are dealing with internally right now that you wish I would ask you about more often?",
        "What is a secret quirk, ritual, or habit of yours that you only ever do when you are completely alone in the house?",
        "When was the last time you felt deeply overwhelmed but chose to pretend everything was completely fine?",
        "What is a small, specific compliment I could give you tomorrow that would genuinely turn your whole day around?",
        "What is an area where you feel like you are trying too hard to meet my expectations instead of focusing on your own?",
        "What is a small childhood habit, preference, or comfort item that you secretly still turn to when you're incredibly stressed?",
        "If you could hand me one specific daily worry or anxiety of yours to hold for the next 24 hours, what would it be?",
        "When you look at the people around us, what is one thing you find yourself secretly comparing your own life to?",
        "What is a boundary you set for yourself recently that you accidentally broke, and how did it make you feel?",
        "What is something you feel you want to apologize to me for, even if it's a tiny detail from a long time ago?",
        "If you could tell me one raw, unfiltered truth about your state of mind right now without any fear of judgment, what would it be?",
        "What is a habit of mine that you’ve had to actively adapt to, even if it took you some time to get used to it?",
        "What does being fully seen by me mean to you—does that thought make you feel safe, or does it make you feel exposed?",
        "What is a piece of your personality that you feel you have to turn down or adjust when we are hanging out with my friends or family?",
        "When was the last time you felt like you were failing at something important to you, and why did you decide to keep it from me?",
        "What is a small, seemingly harmless comment I made recently that actually made you feel judged or criticized?",
        "What is an insecurity you have about our relationship's long-term compatibility that you constantly try to talk yourself out of?",
        "If you could point to a specific moment where you felt emotionally lonely even while lying right next to me, when was it?",
        "What is a personal habit or quirk of yours that you feel overly sensitive about if anyone else points it out?",
        "What is a piece of praise or validation you wish I would say to you more often because you secretly doubt your own ability in that area?",
        "When was the last time you felt completely overwhelmed by a conversation we were having and just wanted to shut down or escape?",
        "What is a part of your daily workload or routine that makes you feel the most inadequate or stressed out right now?",
        "What is something you are afraid to tell me you want or need because you are worried I will see you as too demanding or needy?",
        "What is a specific body language cue or facial expression I make when I am annoyed that completely shuts you down emotionally?",
        "If you could magically erase one minor interaction, text, or comment you made to me recently, what would it be?",
        "What is a situation where you felt like you had to completely mask your true emotions just to keep the peace between us?",
        "What is an area of your life, past or present, where you feel like you are still holding back a small part of yourself from me?",
        "When do you feel the absolute highest amount of internal pressure to be perfect or put-together around me?",
        "What is a past mistake or regret of yours that you worry might change how I look at you if we talked about it in full detail?",
        "What is a specific trigger or situation that instantly makes you feel insecure about your place or priority in my life?",
        "When you are feeling completely emotionally exhausted, what is the worst thing I can do, even if my intentions are entirely good?",
        "What is a standard milestone or expectation of relationships that you secretly feel totally unprepared or unready for?",
        "What is a truth about your current mental health or stress levels that you have been downplaying whenever I ask how you are doing?",
        "What is an aspect of my life, my drive, or my personality that intimidates you just a little bit, even if you admire it?",
        "When was the last time you felt a quiet pang of jealousy or comparison regarding how I interact with someone else in my life?",
        "What is a small, recurring friction point between us that you think we have both been intentionally sweeping under the rug?",
        "If you could ask for a free pass to vent about one minor, recurring annoyance you have with me without me getting defensive, what would it be?",
        "What does being this vulnerable feel like in your body right now—does it feel like a comfortable release, or does it feel like a threat?",
        "What is an area where you feel I don't fully understand your perspective, even after we have talked about it multiple times?",
        "When was the last time you felt like you had to look completely strong for me when you actually just wanted to crumble?",
        "What is a piece of your past that you rarely bring up because you're worried it makes you look messy or disorganized?",
        "What is a specific fear you have about accidentally losing your own identity or independence while building a life with me?",
        "When do you feel the most judged by the outside world, and how does that pressure affect how you interact with me?",
        "What is a small, everyday habit of mine that unexpectedly triggers an old insecurity from your past?",
        "What is something you’ve wanted to tell me about how I handle my bad moods that you’ve kept to yourself to avoid friction?",
        "When was the last time you felt completely invisible in a group setting, and did you wish I had done something to pull you in?",
        "What is a personal goal you are chasing that you secretly feel entirely unqualified or unready to achieve?",
        "What is a perceived expectation you think I have of you that you find completely exhausting to live up to?",
        "When do you feel like you are walking on eggshells around me, even if it's just over something minor?",
        "What is a piece of self-doubt you carry about your career or future that you find yourself constantly hiding behind a confident face?",
        "What is a boundary you've set for yourself in your head that you feel like I constantly cross without realizing it?",
        "When was the last time you wanted a hug or physical comfort from me but felt too proud or stubborn to ask for it?",
        "What is a specific way you feel misunderstood by your own family that you hope I never repeat or make you feel?",
        "What is an automated defense mechanism you use when you feel criticized—do you attack back, explain it away, or completely shut down?",
        "What is a secret frustration you have with how we split our mental or emotional workload as a couple?",
        "When do you feel the most disconnected from me emotionally, and what is usually the root cause of that gap?",
        "What is a personal failure or mistake you made recently that you haven't shared with me because you're scared I'll think less of you?",
        "What is a specific type of reassurance or praise you are absolutely starving for right now, even if you won't admit it?",
        "When was the last time you felt like you were just annoying me by talking about your day or your passions?",
        "What is a part of your body or appearance that you are currently struggling to feel confident about, independent of what I tell you?",
        "What is a recurring anxiety or intrusive thought that plagues your mind when you're trying to fall asleep at night?",
        "If you could ask me to change one small aspect of how I react during a tense moment, what would it be?",
        "What is the most vulnerable thing about your inner world right now that you feel completely terrified to put into words?",
        "What is a piece of advice I gave you recently that you secretly didn't agree with but went along with anyway just to avoid an argument?",
        "When was the last time you felt like my tone or body language was overly dismissive of an emotion you were trying to express?",
        "What is an insecurity you carry about how our relationship handles financial choices, spending habits, or future security?",
        "When you look back at our very first month together, what is a small detail or vulnerability about your life that you intentionally hid from me out of fear of judgment?",
        "What is something you are deeply proud of achieving right now that you feel I haven't fully noticed or properly validated yet?",
        "When do you feel the absolute highest amount of internal pressure to present a sanitized, clean version of your thoughts to me instead of your raw feelings?",
        "What is a specific trigger or phrase of mine that instantly makes you feel like you are being treated like a child instead of an equal partner?",
        "When was the last time you felt a silent emotional distance between us but chose not to speak up because you were just too exhausted to navigate it?",
        "What is a part of your childhood baggage or family history that you worry might subconsciously limit how well you can show up as a partner long-term?",
        "What is a small thing I do when I am stressed or anxious that makes you feel like you have to pack away your own problems to make room for mine?",
        "When do you feel the most self-conscious or insecure about your own intelligence, wit, or logic when we are having a deep conversation?",
        "What is a boundary you honestly wish you had set much earlier in our relationship that you are still clumsily trying to firmly establish now?",
        "When was the last time you secretly hoped I would just notice you were drowning emotionally without you having to explicitly say the words out loud?",
        "What is a personal habit or micro-defense mechanism of yours that you notice flares up the exact second you feel cornered or called out?",
        "What is an aspect of our relationship dynamic that you worry looks completely seamless on the outside but feels a little bit fragile on the inside?",
        "What is a specific compliment I could give you about your character or integrity that would make you feel deeply, truly anchored?",
        "When was the last time you felt like you had to minimize your own achievements or excitement so that I wouldn't feel insecure, stressed, or left behind?",
        "What is a specific, quiet fear you carry about what might happen to our connection if life throws a massive, unpredictable crisis our way?",
        "What is a truth about your current daily energy levels or burnout status that you've been actively masking behind a hyper-productive routine?",
        "When do you feel the most exposed, raw, or uncomfortable when we are actively discussing our emotional boundaries or personal flaws?",
        "What is an area where you feel I have been settling or compromising way too much in our relationship, and why does it worry you?",
        "What is a small, quiet worry you have about how our personalities might shift, harden, or clash as we continue to grow older?",
        "When was the last time you felt a tiny, brief flash of resentment toward me, and what was the exact micro-trigger behind it?",
        "What does it physically look like when your ego is completely bruised during an interaction, and how can I handle that specific moment better?",
        "If you could completely drop the single heaviest internal mask you wear for the outside world, what part of your unpolished self would you finally let breathe around me?",
        "Do you think it’s possible to love someone fully without completely understanding them?",
        "What is the most significant way your priorities have shifted over the last two years?",
        "If you had to describe your relationship with your own mind right now, is it a peaceful place or a battleground?",
        "What is something you think you are trying to prove to the world, and who are you trying to prove it to?",
        "When was the last time you felt a deep sense of envy, and what did it reveal about what you feel you are lacking?",
        "What is a belief or tradition from your family or culture that you have intentionally decided to drop?",
        "If you were forced to live a year of your life in complete isolation, what part of your daily routine would you miss the most?",
        "What is an experience that made you realize you are much stronger or more resilient than you gave yourself credit for?",
        "Do you think you are more prone to over-thinking things until they break, or under-thinking things until they surprise you?",
        "What is a truth about your current mental health or emotional state that you’ve been hiding behind a smile?",
        "If you could see a chart of how you’ve spent your energy over the last year, what category do you think would be dangerously high?",
        "What is something you used to judge others heavily for that you now look at with a lot of empathy and understanding?",
        "How do you handle it when someone you care about deeply makes a massive life choice that you completely disagree with?",
        "What does loyalty mean to you in a practical sense, and what is the ultimate betrayal of that loyalty?",
        "What is an unfulfilled dream of yours that you are terrified to start because you are scared of failing publicly?",
        "Do you find it harder to accept a sincere compliment from someone or to accept a constructive piece of criticism?",
        "What is a specific memory from your childhood that makes you feel instantly safe and protected just thinking about it?",
        "If you had to look at your biggest flaws, which one do you think is actually a twisted version of your greatest strength?",
        "What is an absolute non-negotiable value for you when it comes to the type of people you choose to surround yourself with?",
        "How do you typically react when someone calls you out on a mistake you know you actually made?",
        "What is a question about the universe or existence that keeps you up staring at the ceiling late at night?",
        "Do you think true contentment comes from wanting less or achieving more?",
        "What is a burden or worry you are carrying right now that you would love to just hand over to someone else for a single day?",
        "If you could summarize the most important lesson life has taught you up to this exact moment, what would it be?",
        "What is a truth you have finally accepted about yourself that used to make you feel incredibly insecure?",
        "Do you think it is possible to be truly emotionally independent when you are in a deeply committed relationship?",
        "What is the most significant boundary you have had to set with a family member to protect your own peace?",
        "When you look back at the hardest year of your life, what was the specific turning point that helped you survive it?",
        "What is something you are currently putting a massive amount of effort into that nobody else seems to notice or appreciate?",
        "Do you think your past relationships have made you more guarded, or have they made you more intentional about how you love?",
        "What is a piece of your identity that you feel you have had to sacrifice or tone down as you have gotten older?",
        "How do you handle the feeling of stagnation when life feels repetitive and uninspired?",
        "What is a core value of yours that you would be willing to lose a close friendship over to protect?",
        "When was the last time you felt a profound sense of awe or wonder, and what triggered it?",
        "What is an assumption you made about adulthood when you were a kid that turned out to be completely false?",
        "How do you deal with things that are left unresolved—do you force closure, or are you okay letting things hang in the air?",
        "What is a character trait you see in others that instantly makes you feel safe and comfortable opening up to them?",
        "If you had to identify your absolute biggest emotional blind spot, what do you think it would be?",
        "What is a compliment someone gave you years ago that you still play back in your head when you are feeling low?",
        "Do you think true happiness is a consistent state of mind, or is it just a collection of fleeting, joyful moments?",
        "What is a responsibility or expectation you are currently carrying that feels way too heavy for one person?",
        "How has your definition of a successful life evolved over the last three years?",
        "What is a secret passion or creative outlet you have always wanted to pursue but have hidden out of fear of judgment?",
        "When you are feeling deeply overwhelmed, what is the fastest way for someone to help you ground yourself?",
        "What is a harsh reality about the world that you choose to ignore just to keep your sanity intact?",
        "Do you consider yourself someone who reacts to life as it happens, or someone who actively builds and shapes their circumstances?",
        "What is a memory from your past that used to bring you a lot of joy but now brings you a sense of sadness or nostalgia?",
        "If you could completely erase one negative personality trait of yours instantly, which one are you getting rid of?",
        "What is the most profound lesson you have learned about human connection from a period of intense loneliness?",
        "What is something you are terrified of losing that isn't a person or a material possession?",
        "Do you think you find it easier to love others or to allow yourself to be genuinely loved by them?",
        "What is a specific moment from your past where you felt completely helpless, and how did you regain your footing?",
        "If you could see a visual timeline of your life, what specific era would you label as your true window of self-discovery?",
        "What is a common misconception people have about your emotional availability or openness?",
        "How do you handle the internal sting of being unappreciated when you’ve poured your whole heart into a project or relationship?",
        "What is a personal belief you have about existence or what happens after we die that brings you the most comfort?",
        "When was the last time you felt truly aligned with your authentic self, without putting on a performance for anyone else?",
        "What is the most significant emotional risk you have ever taken in your life, and did the outcome pay off?",
        "Do you think human beings are defined more by the purity of their intentions or by the actual impact of their actions?",
        "What is a piece of historical family baggage or a pattern that you are actively trying your hardest not to repeat?",
        "How do you process deep disappointment when a close friend or mentor completely lets you down?",
        "What is an area of your daily life where you feel like you are constantly fighting an uphill battle against your own instincts?",
        "If you could completely erase one single memory from your brain forever, which specific moment are you wiping out?",
        "What does true vulnerability look like to you when you are at your absolute lowest emotional point?",
        "What is a social issue, cause, or belief that you secretly care about deeply but rarely discuss out loud with anyone?",
        "Do you think your day-to-day ambition is motivated more by a fear of failure or a deep desire for success?",
        "What is a harsh truth about your behavioral patterns that someone called you out on that turned out to be completely accurate?",
        "How do you find meaning, motivation, or structure on days when everything feels completely pointless or exhausting?",
        "What is a personality trait you used to heavily dislike in others that you have recently realized you actually possess yourself?",
        "If you could ask your future self from exactly ten years from now a single question, what would you ask them?",
        "What does emotional maturity look like to you in the heat of a high-stakes argument or disagreement?",
        "What is a secret dream you have for the world or society that you think is completely unrealistic but still hope for?",
        "How do you handle the transition phases of life when one major chapter is clearly ending but the next hasn't started yet?",
        "What is the most profound realization you’ve ever had about your own resilience while experiencing a massive life change?"
    ],
    "Fun": [
        "If you had to enter a competitive eating contest, what food would you choose to stuff your face with?",
        "What is the absolute worst fashion phase you ever willingly went through?",
        "If you were a ghost haunting a house, what mild inconveniences would you cause the new owners?",
        "What is your most useless, random talent or party trick?",
        "If you could swap lives with any fictional character for a week, who would it be?",
        "What is the weirdest food combination that you swear is actually delicious?",
        "If you were arrested with no explanation, what would our friends and family assume you did?",
        "What is a popular trend, movie, or show that everyone loves but you secretly hate?",
        "If you could only use three apps on your phone for the rest of your life, which ones survive?",
        "What would your ultimate, money-is-no-object theme park look like?",
        "What is the dumbest way you’ve ever injured yourself?",
        "If you were a superhero, what would your highly specific, slightly underwhelming superpower be?",
        "What is the funniest or most embarrassing thing that has happened to you in public?",
        "If you won 10 million dollars tomorrow, what is the very first completely ridiculous, unnecessary thing you’d buy?",
        "What is your absolute go-to karaoke song when you’ve had a drink or two?",
        "If you had to survive a zombie apocalypse, which three people we know are on your team?",
        "What is a commercial, jingle, or meme that is permanently rented space in your brain?",
        "What’s the worst movie you have ever watched from start to finish?",
        "If you could talk to one species of animal, which one would you choose and what would you ask them?",
        "What is your most controversial opinion about something completely trivial (like cereal or toilet paper orientation)?",
        "If your pet could suddenly talk for five minutes, what is the first thing they’d roast you for?",
        "What was your very first screen name, gamertag, or email address?",
        "If you had to dress up in a couples' costume for Halloween, what is your dream duo?",
        "What is the most ridiculous lie you were told as a kid that you believed for way too long?",
        "If you were forced to replace your left hand with an object instead of a prosthetic, what object would be the funniest or most useful?",
        "What is a specific smell that you absolutely love, even though most people would find it weird or gross?",
        "If you had to create a signature cocktail named after your current lifestyle, what would be the ingredients and the name?",
        "What is the most ridiculous hill you are absolutely willing to die on?",
        "If you could have any mythical creature as a fully trained, well-behaved house pet, what are you picking?",
        "What is the most chaotic thing you have ever witnessed happen at a grocery store or mall?",
        "If you had to dress exclusively in one color for the next five years, which color are you choosing?",
        "What is a skill or hobby that looks incredibly cool when other people do it, but looks completely tragic when you try?",
        "If you were a wrestler, what would be your dramatic walk-out song and your signature move?",
        "What is the most bizarre dream you’ve ever had that you can still remember perfectly today?",
        "If you could delete one single invention from human history so it never existed, what would it be?",
        "What is the absolute worst meal you have ever cooked for yourself or someone else?",
        "If you were guaranteed to be completely immune to the law for exactly one hour, what is your master plan?",
        "What is a luxury item or experience that you think is a total scam and completely overhyped?",
        "If you could instantly become a world-class expert in one incredibly specific trivia category, what would it be?",
        "What is the most embarrassing song on your current playlist that you would immediately skip if someone else got in the car?",
        "If you had to spend a week living inside any video game universe, which one gives you the best odds of survival?",
        "What is the dumbest argument you have ever gotten into with a friend or family member?",
        "If you had to pick one reality TV show to be a contestant on, which one do you think you’d actually win?",
        "What is a weird childhood habit or ritual that you secretly kept doing way longer than you should have?",
        "If you were given a million dollars but you had to spend it all inside a single dollar store in 24 hours, what are you buying?",
        "What is your absolute ultimate comfort food when you are sick, sad, or just totally exhausted?",
        "If you could swap voices with any celebrity for a month, whose voice are you stealing?",
        "What is the strangest or most useless piece of random information you have stored in your brain?",
        "If you were forced to open a niche museum, what specific collection or theme would your museum showcase?",
        "If you had to delete one social media platform from the internet forever, which one is going down?",
        "What is the most ridiculous thing you bought online while completely bored or sleep-deprived?",
        "If you were forced to live in a house shaped like a giant food item, what food are you choosing?",
        "What was your absolute favorite toy or cartoon character as a kid that you were oddly obsessed with?",
        "If you could have the entire cast of any TV show show up to your birthday party, which show are you picking?",
        "What is the most illegal-feeling thing that is completely legal to do?",
        "If you had to replace your car horn with a sound effect or a movie quote, what would it be?",
        "What is the weirdest or most specific rule your parents had in your house growing up?",
        "If you were a chef opening a restaurant that only serves one single dish cooked 50 different ways, what is the dish?",
        "What is a movie that you know is absolute trash, but you will still sit down and watch it if it’s on?",
        "If you could instantly learn to play any musical instrument perfectly, but you could only play it while standing on one foot, what instrument is it?",
        "What is the most useless piece of advice a teacher or mentor ever gave you?",
        "If you were forced to participate in a reality TV show about wilderness survival, how many days do you honestly last?",
        "What is a popular food item that you think smells amazing but tastes absolutely terrible?",
        "If you could turn any everyday chore (like folding laundry or washing dishes) into an Olympic sport, which one would you win a gold medal in?",
        "What is the most embarrassing thing you have ever accidentally said to a stranger?",
        "If you could have a conversation with any historical figure, but you have to do the entire interview in a terrible accent, who are you talking to?",
        "What is your absolute biggest, pettiest pet peeve when it comes to driving or traffic?",
        "If you were a mad scientist, what two animals are you cross-breeding to create the ultimate chaotic creature?",
        "What is the worst haircut or hairstyle you have ever actively rocked in your life?",
        "If you could command a small army of 500 tiny creatures (like squirrels or frogs), what is your first mission?",
        "What is a conspiracy theory that is completely harmless but you secretly find hilarious or convincing?",
        "If you had to give a 20-minute presentation right now with absolutely zero preparation, what topic are you talking about?",
        "What is the most ridiculous lie you have ever told to get out of a social commitment?",
        "If your current state of mind was represented by a cartoon sound effect, what sound would it be right now?",
        "If you were forced to rename yourself after a household appliance, what name are you going by?",
        "What is the most ridiculous or dramatic reason you have ever seen a child throw a massive temper tantrum in public?",
        "If you could command a single flock of 100 birds to follow someone around for a day, who is your target?",
        "What is a popular movie quote that you constantly use in conversation, even if nobody else gets the reference?",
        "If you were an NPC (Non-Player Character) in a video game, what repetitive line would you mutter whenever someone walks past you?",
        "What is the single worst or most disappointing text message you have ever received from a wrong number?",
        "If you had to create a fake holiday dedicated entirely to your favorite lazy activity, what is it called and how do we celebrate?",
        "What is a completely harmless thing that always makes you feel like an absolute criminal when you do it?",
        "If you had to choose one flavor of ice cream to be completely wiped off the face of the Earth forever, which one is going down?",
        "What is the most absurd or useless item you have ever successfully sold or bought at a garage sale or online marketplace?",
        "If you were given a million dollars but could only spend it on upgrading a single room in our house to a ridiculous extreme, which room gets the upgrade?",
        "What is your absolute ultimate, non-negotiable rule when it comes to the perfect movie theater snacking experience?",
        "If you could instantly summon one fast-food item to appear in your hand right now out of thin air, what are we eating?",
        "What is a kids' movie or show that you watched recently that you think is genuinely better written than most adult entertainment?",
        "If you had to spend an entire week speaking exclusively in rhymes, how long do you think you’d last before losing your mind?",
        "What is the most dramatic, over-the-top way you have ever seen someone quit a job or a school project?",
        "If you were a superhero whose powers were entirely determined by the last thing you ate, what is your superhero name and ability?",
        "What is a weirdly specific talent or piece of knowledge you have that is completely useless unless you are in a very specific scenario?",
        "If you had to replace all the windows in our house with stained glass depicting a single meme, which meme are we showcasing to the neighborhood?",
        "What is the single funniest or most chaotic misunderstanding you have ever had because of a text message typo?",
        "If you were forced to live a year of your life inside a specific decade from history, which era has the best vibe for you?",
        "What is a massive, widely accepted social norm that you think is completely stupid and wish we would all just stop doing?",
        "If you were a professional standard-size wrestler, what would be your incredibly intimidating signature entrance outfit?",
        "What is the most ridiculous lie a salesperson or commercial ever successfully convinced you to buy into?",
        "If you could create a brand new, highly chaotic Olympic sport using only items found in a typical kitchen, what are the rules?",
        "If you had to join a circus, what completely made-up act would you perform?",
        "What is the most ridiculous fashion trend you secretly want to see make a major comeback?",
        "If you could replace the sound of heavy rain with any other noise, what would it be?",
        "What is a kid's game you would absolutely dominate if you played it against a group of adults today?",
        "If you could have an unlimited supply of one specific dipping sauce for the rest of your life, what is it?",
        "What is the weirdest or most unconventional thing you have ever used as a makeshift bookmark?",
        "If you were a cartoon supervillain, what would your dramatic evil laugh sound like?",
        "What is a popular slang word used today that makes you feel incredibly ancient whenever you hear it?",
        "If you had to open a themed restaurant where every waiter dresses like a specific historical figure, who are you picking?",
        "What is the funniest or most absurd nickname you have ever heard someone give to a pet?",
        "If you could permanently ban one household chore from existing globally, which one is going down?",
        "What is the most random or chaotic item currently sitting inside your glove compartment or car trunk?",
        "If you were a professional wrestler, what would your hype man say about you to intimidate the opponent?",
        "What is a movie plot that makes absolutely zero sense when you try to explain it out loud to someone?",
        "If you could instantly learn any traditional folk dance perfectly, which one would look the most hilarious?",
        "What is the strangest or most baffling thing you have ever witnessed someone do while waiting at a red light?",
        "If you could turn any minor everyday inconvenience into a mild superpower, what would your ability be?",
        "What is a popular food item that you think requires way too much baseline effort to actually eat?",
        "If you were forced to live inside a specific sitcom universe for a full month, which one would be the most stressful?",
        "What is the most ridiculous text message you have ever sent to the completely wrong person?",
        "If you had to create a brand new animal by combining a sea creature and a land mammal, what are we getting?",
        "What is a commercial jingle from your childhood that still regularly gets stuck in your head?",
        "If you could replace all the grass in the world with a different material, what would be the funniest option?",
        "What is the most chaotic piece of decoration you would put in your dream room if money wasn't an issue?",
        "If your current state of mind was represented by a specific type of vehicle, what are you driving right now?",
        "If you were forced to spend a year living inside a giant hollowed-out pumpkin, what major changes would you make to the interior design?",
        "What is the single most ridiculous argument you have ever witnessed two complete strangers get into in public?",
        "If you could replace all the doorbells in the world with a specific sound effect from an old cartoon, what noise are you picking?",
        "What is a popular movie that everyone calls a absolute masterpiece but you think is a total chore to sit through?",
        "If you could command an army of 1,000 pigeons to perform a coordinated flash mob dance, where are you sending them?",
        "What is the weirdest or most specific rule you would implement if you were suddenly elected the ruler of a tiny island nation?",
        "If you were given a million dollars but could only spend it on building the world's most over-the-top treehouse, what features are you adding?",
        "What is the absolute worst piece of fashion advice you ever willingly took from a magazine or a celebrity?",
        "If you had to change your legal name to a combination of your favorite fruit and your least favorite household chore, what is your new name?",
        "What is the funniest or most absurd thing you have ever accidentally dropped down a public toilet or a sink drain?",
        "If you could instantly acquire the ability to perfectly mimic any celebrity's voice, whose voice are you stealing first?",
        "What is a completely harmless superstition that you secretly follow anyway, just in case?",
        "If your life was a video game, what ridiculous item would your body drop as loot when you are finally defeated?",
        "What is the most bizarre food combination that you have ever seen someone eat with absolute confidence and enjoyment?",
        "If you could banish one specific word from the dictionary forever because it sounds inherently annoying to you, what word is it?",
        "What is the single dumbest way you have ever lost a completely fair bet with a friend?",
        "If you had to open a retail business that only sells things that are completely useless, what would be your signature best-selling item?",
        "What is a popular trend from your teenage years that makes you cringe instantly when you look back at old photos?",
        "If you could turn any minor everyday task into a dramatic action movie sequence, which chore are you picking?",
        "What is the most ridiculous lie you ever told a teacher or a boss to cover up for being late or missing a deadline?",
        "If you had to survive a full week stranded on a deserted island with a single fictional villain, who are you choosing?",
        "What is a standard household object that you think looks lowkey terrifying if you stare at it in the dark for too long?",
        "If you were forced to choose a single song to play at maximum volume every time you enter a room, what is your entrance theme?",
        "What is the funniest or most chaotic misunderstanding you have ever experienced due to a bad translation or a thick accent?",
        "If you could give a 15-minute lecture on any completely fictional or made-up topic, what would your presentation be called?"
    ],
    "Spicy": [
        "What is a fantasy or scenario you’ve thought about but haven't actually told me yet?",
        "Where is the most adventurous or riskiest place you’ve ever thought about doing it with me?",
        "What is something I do in bed that instantly drives you crazy or turns you on?",
        "If you could choose exactly what I wear to bed tonight, what would it be?",
        "What is your favorite time of day to get intimate—morning, afternoon, or late night?",
        "What is a specific touch, look, or phrase I use that signals to you that I'm in the mood?",
        "Do you prefer it when things are slow, romantic, and gentle, or fast, rough, and passionate?",
        "What is the best sex we’ve ever had, in your opinion? Describe that memory.",
        "What is a part of your body that you consider an underrated turn-on when touched?",
        "How do you feel about dirty talk—does it turn you on, or does it make you laugh?",
        "If we were to buy a new toy, outfit, or accessory together, what category are you looking at first?",
        "What is a sexual boundary or hard no for you that you want to make sure we always respect?",
        "What is something you’ve watched or read that unexpectedly turned you on?",
        "If you could choose one place outside of the bedroom for us to hook up right now, where would it be?",
        "What is your favorite position, and what do you love most about it?",
        "How do you feel about roleplay, and is there a specific character or dynamic you’d want to try?",
        "What is the most memorable dream you’ve ever had about me?",
        "What is something I could do during the day to build anticipation for later tonight?",
        "Do you like being in complete control, giving up control, or switching it up?",
        "What is a physical feature of mine that you find yourself staring at when you're feeling playful?",
        "What is your opinion on public displays of affection (PDA)—how much is too much?",
        "If you could give me an explicit command right now that I had to follow, what would it be?",
        "What is a sensory trigger that gets you in the mood (a specific scent, lighting, music, temperature)?",
        "What is the most satisfying part of our intimate life right now, and what’s one thing you want more of?",
        "If we could only use our hands and mouths tonight, what would you want me to do to you first?",
        "What is a part of my body that you think doesn't get enough attention when we get intimate?",
        "If you could script the perfect morning-after scenario with me, what does it look like from the moment we wake up?",
        "What is the absolute wildest or most daring thing we have ever done together physically?",
        "If I told you I wanted to try something completely new in bed tonight, what is the first thing you'd hope it was?",
        "What is your favorite type of lingerie, clothing, or style that you find completely irresistible on me?",
        "Do you prefer the lights completely on, totally pitch black, or somewhere moody in between?",
        "What is a specific memory of us hooking up that randomly pops into your head during the workday?",
        "How do you feel about the idea of blindfolds, restraints, or mild sensory deprivation?",
        "What is the biggest physical turn-off for you that can instantly ruin the mood, no matter how hot things are?",
        "If you could choose one song to play in the background right now while we make out, what are we putting on?",
        "What is a fantasy you have that involves a specific location or setting outside of our house?",
        "Do you like it when I take the initiative and am aggressive, or do you prefer to take charge and dictate the pace?",
        "What is something you like me to do with my hands while we are intimately connected?",
        "If we were playing a game where every piece of clothing removed required a truth, how fast would you try to win?",
        "What is your honest opinion on quickies—do you find them incredibly exciting, or do you prefer a long build-up?",
        "What is a text message or picture I could send you while you're at work that would make it impossible for you to focus?",
        "When we are kissing, what is the difference between a 'romantic' kiss and a kiss that means I want you right now?",
        "What is a part of your own body that you feel the most confident or sexy about when we are together?",
        "If you could choose anywhere on my body for a slow, teasing massage tonight, where are you starting?",
        "What is something we used to do early on in our physical relationship that you miss or want to bring back?",
        "Do you find eye contact during intimacy to be intensely hot, or does it make you feel a little too exposed?",
        "What is a boundary you’ve thought about pushing slightly with me, just to see how it feels?",
        "If you could describe my sexual energy or vibe in bed using a single word, what would it be?",
        "What is the most unexpected thing I’ve ever done during sex that turned you on immensely?",
        "If we had the entire house to ourselves for a full 24 hours, how many times do you think we’d end up hooking up?",
        "What is a specific physical position or angle we haven't tried yet that you’ve been curious about?",
        "If we were to set a timer for exactly five minutes, what is the most teasing thing you would do to me?",
        "What is something you think I do completely naturally that makes me look incredibly sexy, even when I’m not trying?",
        "If we were to make a playlist specifically for the bedroom, what are the first three songs you are adding?",
        "How do you feel about the idea of ice, heat creams, or playing with different temperatures during intimacy?",
        "What is a part of my body that you feel is completely underappreciated by anyone else, but turns you on instantly?",
        "If you could text me a single word right now to tell me exactly what you want to do to me later, what word are you choosing?",
        "What is your favorite type of lighting when we are getting physical—candles, neon lights, or dim lamps?",
        "Do you prefer it when I am slow and teasing with my touch, or when I move with absolute certainty and urgency?",
        "What is the most explicit or memorable dream you have ever had about us that you haven't shared yet?",
        "If you could choose one piece of clothing of mine that you get to rip or tear off tonight, what is it?",
        "What is a fantasy of yours that involves a mirror, and how do you want us to use it?",
        "How do you feel about the concept of a slow burn—spending hours teasing each other throughout the day before actually touching?",
        "What is something you’ve always wanted to say to me while we are in the middle of sex, but haven’t quite had the confidence to blurts out?",
        "If you could choose a specific location in a hotel or a vacation spot for us to get adventurous, where would it be?",
        "What is a physical sensation (like a scratch, a bite, or a pull) that you find unexpectedly arousing?",
        "If you could watch a video playback of any single intimate moment we’ve ever shared, which one are you picking?",
        "What is your honest opinion on shower sex—is it highly romantic and hot, or is it just a logistical nightmare?",
        "What is something I do with my eyes or my expression when we are hooking up that completely gives away how much pleasure you're giving me?",
        "If you had to choose between me being completely vocal or completely silent during intimacy tonight, which one turns you on more?",
        "What is a secret trigger or thought that can instantly get you in the mood, even if you were completely distracted a minute before?",
        "If we were playing a game where the winner gets to dictate every physical move for the next hour, how competitive are you going to get?",
        "What is a specific type of fabric or material (like silk, leather, or lace) that you find intensely sexy to touch on my skin?",
        "If you could give me a massage tonight with absolutely no expectations of it leading anywhere, where would you want to spend the most time touching me?",
        "What is the most intense wave of pleasure you think we have ever shared together in a single moment?",
        "If you could lock me in a room with you tonight and tell me exactly three things I am not allowed to do, what are the rules?",
        "What is a specific physical feature of mine that you think gets significantly sexier when we are in the heat of the moment?",
        "If we were to try a completely different setting for intimacy tonight—like the kitchen counter or the living room floor—where are you picking?",
        "What is the most teasing or provocative thing I could whisper in your ear while we are out at a crowded dinner party?",
        "How do you feel about the idea of using mirrors to watch ourselves while we are intimately connected?",
        "What is a specific memory of us hooking up that you think about whenever you need a quick mental escape during a stressful day?",
        "If you could choose a specific outfit for me to wear around the house today with absolutely nothing underneath it, what am I wearing?",
        "What is your honest opinion on giving or receiving a lap dance—is it something you’d want to try with me tonight?",
        "What is a part of your body that you think is an incredibly sensitive turn-on, but we rarely focus on it during sex?",
        "If you could script the absolute perfect, uninterrupted 3-hour window for us to just focus on physical pleasure, how does it start?",
        "Do you prefer the intensity of making out when we are both completely breathless, or a slow, deep, intense kiss that lingers?",
        "What is a specific text message or photo I could send you right now that would guarantee you’re thinking about bed for the rest of the evening?",
        "If we were playing a game where every time you touch me, you have to use a different part of your body (hands, lips, tongue), where are you starting?",
        "What is a fantasy or scenario from a movie or a book that you secretly want us to recreate together in real life?",
        "How do you feel about the concept of edge-playing or deliberately delaying pleasure to make the final moment infinitely more intense?",
        "What is something I do with my breathing or my voice when things get intense that drives you completely wild?",
        "If you could choose one place outdoors where we could guaranteed not get caught, what adventurous backdrop are you choosing?",
        "What is a specific type of touch—like a light trace of the fingernails or a firm grip—that gives you instant goosebumps?",
        "If you had to describe my sexual personality using a specific element (fire, water, earth, or air), which one fits me best in bed?",
        "What is a question about my hidden desires or turn-ons that you’ve been dying to ask me but haven’t found the right moment for?",
        "If we were to buy a brand new accessory or toy for the bedroom tonight, who gets to pick it out and test it first?",
        "What is the most intense, electrifying wave of physical chemistry you think we have ever felt just by looking at each other across a room?",
        "If you could give me a highly detailed command right now regarding what you want me to do to you tonight, what are the exact instructions?",
        "What is an aspect of our intimate life right now that makes you feel the most physically confident and secure as a partner?",
        "If tonight was the absolute last time we could ever get physical, what is the ultimate, unforgettable encounter you would design for us?",
        "What is a specific physical boundary you’ve thought about testing with me just to see how it turns us both on?",
        "If we were to play a game where the loser has to do whatever the winner wants in bed, how competitively would you play?",
        "What is something you’ve watched or read recently that made you immediately think about wanting to touch me?",
        "If you could pick a single room in a completely empty mansion for us to explore intimately, where are we going first?",
        "What is the single sexiest text message or picture you have ever received from me that you still think about?",
        "How do you feel about the idea of using a blindfold on me tonight while you completely take control?",
        "What is a specific type of clothing or fabric you find completely irresistible when it is halfway pulled off my body?",
        "If you could script the absolute perfect, uninterrupted morning encounter with me tomorrow, what does it look like?",
        "What is something I do with my hands or lips during sex that instantly makes you lose your train of thought?",
        "Do you prefer the intensity of a quick, passionate encounter against a wall, or a slow, hours-long buildup in bed?",
        "What is a part of your body that you feel is incredibly sensitive, but we rarely focus on it during intimacy?",
        "If we were out at a busy bar right now, what is a subtle touch or look you would give me to let me know you're ready to go home?",
        "What is a fantasy of yours that involves a specific time of day or unique outdoor lighting?",
        "How do you feel about dirty talk—is there a specific word or phrase I could use tonight that would drive you crazy?",
        "If you could choose exactly what I wear to bed tonight, with the understanding that it won't stay on for long, what is it?",
        "What is the most adventurous or riskiest place you have ever actually fantasized about us getting caught?",
        "Do you like it more when I am completely vocal about what feels good, or do you prefer to read my body language?",
        "What is a specific intimate memory of us that randomly pops into your head when you are sitting in a boring meeting or class?",
        "If you could buy any new accessory, toy, or game for the bedroom tonight without any hesitation, what category are you looking at?",
        "What is a physical feature of mine that you find yourself staring at when we are just hanging out, feeling playful?",
        "If you could give me a highly detailed, explicit instruction right now that I had to follow tonight, what would you say?",
        "What is your honest opinion on using oils or lotions for a full-body, teasing massage before we actually touch?",
        "What is the most satisfying part of our intimate life right now, and what is one small thing you want even more of?",
        "If we could only use our mouths and hands tonight, what is the first thing you would want me to do to you?",
        "What is the absolute highest level of physical chemistry you think we have ever reached in a single night together?",
        "What is a specific physical position or angle we haven't tried yet that you’ve been curious about?",
        "If we were to set a timer for exactly five minutes, what is the most teasing thing you would do to me?",
        "What is something you think I do completely naturally that makes me look incredibly sexy, even when I’m not trying?",
        "If we were to make a playlist specifically for the bedroom, what are the first three songs you are adding?",
        "How do you feel about the idea of ice, heat creams, or playing with different temperatures during intimacy?",
        "What is a part of my body that you feel is completely underappreciated by anyone else, but turns you on instantly?",
        "If you could text me a single word right now to tell me exactly what you want to do to me later, what word are you choosing?",
        "What is your favorite type of lighting when we are getting physical—candles, neon lights, or dim lamps?",
        "Do you prefer it when I am slow and teasing with my touch, or when I move with absolute certainty and urgency?",
        "What is the most explicit or memorable dream you have ever had about us that you haven't shared yet?",
        "If you could choose one piece of clothing of mine that you get to rip or tear off tonight, what is it?",
        "What is a fantasy of yours that involves a mirror, and how do you want us to use it?",
        "How do you feel about the concept of a slow burn—spending hours teasing each other throughout the day before actually touching?",
        "What is something you’ve always wanted to say to me while we are in the middle of sex, but haven’t quite had the confidence to blurts out?",
        "If you could choose a specific location in a hotel or a vacation spot for us to get adventurous, where would it be?",
        "What is a physical sensation (like a scratch, a bite, or a pull) that you find unexpectedly arousing?",
        "If you could watch a video playback of any single intimate moment we’ve ever shared, which one are you picking?",
        "What is your honest opinion on shower sex—is it highly romantic and hot, or is it just a logistical nightmare?",
        "What is something I do with my eyes or my expression when we are hooking up that completely gives away how much pleasure you're giving me?",
        "If had to choose between me being completely vocal or completely silent during intimacy tonight, which one turns you on more?",
        "What is a secret trigger or thought that can instantly get you in the mood, even if you were completely distracted a minute before?",
        "If we were playing a game where the winner gets to dictate every physical move for the next hour, how competitive are you going to get?",
        "What is a specific type of fabric or material (like silk, leather, or lace) that you find intensely sexy to touch on my skin?",
        "If you could give me a massage tonight with absolutely no expectations of it leading anywhere, where would you want to spend the most time touching me?",
        "What is the most intense wave of pleasure you think we have ever shared together in a single moment?"
    ],
    "Romantic": [
        "What was the exact moment you realized you were falling in love with me?",
        "What is a small, everyday habit of mine that secretly makes you smile?",
        "If our relationship was a movie or a book title, what would it be called?",
        "What is your favorite memory of us from our first few months of dating?",
        "When do you feel the most physically and emotionally safe with me?",
        "What is a song that always makes you think of me when you hear it?",
        "If we could pack a bag right now and go anywhere in the world together, where are we going?",
        "What is something I did recently that made you feel incredibly appreciated?",
        "How do you think we have changed or grown as a couple since we first met?",
        "What is your favorite physical feature of mine to look at when we're just talking?",
        "What does your ideal, no-phones, completely free date night look like?",
        "What is a compliment I gave you that stuck with you long after I said it?",
        "In what ways do you think we balance each other out or complement each other's personalities?",
        "What is a dream or a goal you have for our future together over the next five years?",
        "If you could relive one single day from our past together, exactly as it happened, which day would you choose?",
        "What is something new you'd love for us to try or learn together this year?",
        "How do you best receive love? (Words of affirmation, touch, gifts, quality time, or acts of service?)",
        "What is a secret nickname or thought you had about me before we started dating?",
        "When we are apart, what is the specific thing you miss the most about my presence?",
        "What is something you think we do better as a couple than most other people?",
        "What is a tradition you want us to start and keep doing for years to come?",
        "What is the most romantic thing you think someone could do for you?",
        "Do you believe in soulmates, and do you think we fit that description?",
        "What is a text message I sent you that you’ve secretly saved or re-read?",
        "What is one thing you hope never, ever changes about our relationship?",
        "What is something I did or said early on in our relationship that made you realize I was different from everyone else?",
        "If you could capture one specific sound or laugh of mine to listen to whenever you're stressed, which one would it be?",
        "What is a physical habit of mine when I'm sleeping or waking up that you find incredibly endearing?",
        "When we are sitting in complete silence together, what goes through your mind?",
        "What is a way I show love that you appreciated, even if it took you a little while to notice it?",
        "If you could freeze time during one specific moment we’ve shared together, which moment are we freezing?",
        "What is a topic or hobby you had zero interest in before meeting me, but now love because of me?",
        "What is something you think our relationship has taught you about yourself that you didn't know before?",
        "When do you feel the most proud to walk into a room holding my hand?",
        "What is a small, inexpensive gift I’ve given you that holds the highest sentimental value to you?",
        "If you were writing a love letter to me right now, what is the core message or feeling you’d want to get across?",
        "What is a subtle sign or cue you give when you just want me to hold you or be close to you?",
        "What is your favorite way for us to reconcile or reconnect after we’ve had a disagreement or a stressful day?",
        "If our love story had a specific theme song or soundtrack, what genre of music would it be?",
        "What is a dream about our future house, family, or lifestyle that you haven't mentioned out loud yet?",
        "What is an inner strength or quality of mine that you rely on when things get tough for you?",
        "If you could plan a surprise date for me with an unlimited budget, what is the first thing we are doing?",
        "What is a specific phrase or word I use often that you’ve started using yourself?",
        "When you look at me when I'm not paying attention, what are you usually thinking about?",
        "What is a memory of us that always makes you feel incredibly warm and nostalgic, no matter how long ago it happened?",
        "In what ways do you feel like our relationship creates a safe space for you to be your absolute weirdest self?",
        "What is a question you’ve been wanting to ask me about our relationship but have been waiting for the right moment?",
        "What is something you think we should celebrate more often as a couple that we currently overlook?",
        "If you could describe the feeling of our love using only three distinct adjectives, what would they be?",
        "What is one thing you want to make sure we always prioritize, no matter how busy or chaotic life gets?",
        "What is a specific way I support you or show up for you that makes you feel invincible?",
        "If you could design a custom piece of jewelry or a token that perfectly represents our relationship, what would it look like?",
        "What is a quirky or unique language or inside joke we share that you love the most?",
        "When did you first realize that you could trust me with your absolute deepest, darkest secrets?",
        "What is something you think I understand about you better than your closest friends or family members do?",
        "If we could recreate our very first date tonight but change one detail to make it even better, what would you change?",
        "What is a specific look I give you that tells you everything is going to be okay, no matter what?",
        "In what way do you think our relationship has made you a more gentle or understanding person?",
        "What is a dream vacation or milestone experience that you refuse to do with anyone else but me?",
        "What is a small text message or note I left you that completely turned a bad day around for you?",
        "When we are out in public together, what is a subtle way you like to remind me that you're glad you're with me?",
        "What is a strength of ours as a couple that you think will help us get through any future hardships?",
        "If you could pinpoint the exact moment you felt our relationship shift from dating to building a life together, when was it?",
        "What is a physical sensation or feeling you get only when you are wrapped tightly in my arms?",
        "What is an aspect of my personality or character that inspires you to be a better version of yourself?",
        "If you had to pick a specific flower, element, or landscape that matches the energy of our love, what would it be?",
        "What is something you think I do completely effortlessly that always leaves you a little bit in awe?",
        "How do you think our definitions of romance have changed since we first started dating?",
        "What is a specific memory of us overcoming a disagreement or misunderstanding that actually made you love me more?",
        "If you could give our relationship a guiding motto or family crest for the future, what would the words be?",
        "What is a hidden talent or passion of mine that you want to see me explore or show off more to the world?",
        "When you think about us growing old together, what is the specific image or scene that comes to your mind?",
        "What is a way that I make you feel intensely desired, not just physically, but emotionally and intellectually?",
        "If you could tell me one thing that you don't think I hear enough from you, what would it be?",
        "What is the greatest gift that being in this relationship has given to your everyday life?",
        "What is a specific way I touch your hair, face, or hands that instantly makes you feel grounded and calm?",
        "If you had to write a poem or a single sentence that captures the exact essence of how I make you feel, what would it say?",
        "What is an underrated quality of mine that you think doesn't get enough praise from the outside world?",
        "When you think about the word us, what is the very first mental image or memory that flashes in your mind?",
        "What is a dream or goal of mine that you are completely invested in helping me achieve?",
        "If you could take a snapshot of my face during one specific moment of our day, which expression are you saving forever?",
        "What is a way that being with me has changed how you look at your own future?",
        "When we are caught in a busy or stressful room full of people, what is our secret signal to each other that we’re ready to leave?",
        "What is a specific sacrifice you've seen me make for our relationship that made you respect me even more?",
        "If you could give me a superpower that would make my daily life 100 times easier, what superpower am I getting?",
        "What is a specific habit or character trait of mine that you hope our future children or family members inherit?",
        "When do you feel the most intellectually stimulated or challenged by a conversation we are having?",
        "What is a piece of clothing of mine that you secretly love to see me wear because you think I look incredible in it?",
        "If you could hear my thoughts for exactly five minutes, during what part of the day would you want to tune in?",
        "What is a reassurance or a reminder that I give you that you need to hear the most when you’re feeling insecure?",
        "What is a specific adventure or risk you took with me that you were terrified of at first but now love?",
        "If our relationship was an anchor, what specific storm or hard time did it keep us steady through?",
        "What is a little domestic moment we share (like cooking, grocery shopping, or cleaning) that you secretly look forward to?",
        "What is something you think I do that shows how much I love you without me ever having to say the actual words?",
        "If you could ask me to promise you one thing about our emotional future together, what promise do you want?",
        "What is an aspect of our connection that feels totally effortless, like it was always meant to be that way?",
        "When you look back at who you were before we started dating, how do you think our love has helped you heal?",
        "What is a specific goal or milestone we hit as a couple that made you think, Wow, we really are an incredible team?",
        "If you could give me one massive thank-you for something I did that went completely unacknowledged, what would it be for?",
        "What is the most permanent, unchanging truth about how much you love me that you want me to carry with me forever?",
        "What is a specific way I look at you or smile at you that makes you feel instantly attractive and valued?",
        "If you could translate the exact feeling of our relationship into a physical texture, what would it feel like?",
        "What is an inside joke or shared routine of ours that always manages to diffuse tension when we are stressed?",
        "When did you first realize that being vulnerable with me wasn't dangerous, but actually brought us closer?",
        "What is something I do to show you affection that you think is completely unique to our relationship?",
        "If we could go back to the very first week we met, what is the one piece of advice you would give us?",
        "What is an area of my life or personality where you feel like you are my absolute biggest cheerleader?",
        "When we are physically separated for a while, what is the first thing you want to do the second we see each other again?",
        "What is a specific goal or milestone we achieved together that made you realize we can handle absolutely anything?",
        "If you had to pick a single word that describes the baseline emotional atmosphere of our home, what word is it?",
        "What is a small, quiet moment we shared recently that made you feel an overwhelming rush of gratitude for us?",
        "In what way do you think my love has given you the confidence to take bigger risks in your outside life?",
        "What is a subtle habit of mine that you notice when I am trying to hide that I am tired or stressed out?",
        "If our love story was adapted into a piece of music, what instruments would be playing the main melody?",
        "What is a specific reassurance I give you that makes you feel the most secure about our long-term future?",
        "What is a dream vacation or spontaneous adventure you have been secretly planning in your head for us to take?",
        "How do you think our communication style has improved or matured since the early days of our relationship?",
        "What is a part of my daily routine that you love to quietly observe when I think you aren't paying attention?",
        "What is a specific way that being your partner has helped you heal from an old emotional wound or heartbreak?",
        "If you could give me a custom award for a specific way you appreciate me as a partner, what would the title of the award be?",
        "What is a topic we can talk about for hours without ever getting bored or running out of things to say?",
        "When do you feel the most intensely proud to tell people that you are my partner?",
        "What is a small domestic habit we have developed together that you hope we keep doing for the rest of our lives?",
        "If you could ask me to magically take over one of your daily stresses or anxieties, which one would you hand over?",
        "What is the most beautiful thing about the life we are building together that you never expected to find?",
        "What is a specific phrase or tone I use when I’m talking to you that instantly makes you feel wrapped in absolute warmth?",
        "If you could describe the energy and feeling of our very first kiss using a specific color or landscape, what would it be?",
        "What is a little habit of mine that you always notice when I am trying my best to make you feel special or cared for?",
        "When did you first realize that our relationship wasn’t just a passing phase, but something genuinely built to last?",
        "What is a unique way that we handle external stress together that makes you feel incredibly secure in our partnership?",
        "If we could bottle up the exact atmosphere of one specific rainy afternoon or lazy day we spent together, which one are we choosing?",
        "What is an unexpected way that my baseline presence has brought peace to a historically chaotic part of your life?",
        "When do you feel the most deeply connected to my thoughts, mind, and intellect during a conversation?",
        "What is a small token, item, or piece of clothing of mine that you love to keep close to you when we are apart for a while?",
        "If you had to write a dedication page to me in a book about your life journey, what would the very first sentence say?",
        "What is a specific way that I support your personal growth and ambitions without ever smothering your independence?",
        "When you look at me across a crowded, loud room, what is the exact thought that automatically loops in your brain?",
        "What is a shared goal or dream of ours that you look forward to working toward the most over the next twelve months?",
        "What is a subtle way that I show you I'm actively listening and processing your words, even when I'm completely exhausted?",
        "If you could capture one specific chuckle or laugh of mine to keep on a mental audio loop for stressful days, which laugh is it?",
        "What is a way that being in this relationship has completely changed your old perspective on what a healthy partnership looks like?",
        "When do you feel the most physically cherished, protected, and valued by me outside of any physical or bedroom context?",
        "What is a small domestic chore, ritual, or task that we do together that secretly feels deeply romantic and grounding to you?",
        "If you could choose one memory of us to be turned into a permanent oil painting on our living room wall, which memory is it?",
        "What is a question about our shared future or lifestyle that you love to daydream about when you can't fall asleep?",
        "What is an aspect of my personality or character that you think completely balances out one of your heaviest quirks?",
        "When did you first feel the distinct sensation that you didn't have to wear a mask or filter your thoughts around me at all?",
        "What is a specific text message I sent you in the past that completely shifted your mood from terrible to amazing?",
        "If you could guarantee that we keep one specific tradition or habit alive for the next twenty years, what would it be?",
        "What is the most beautiful unwritten, unspoken rule of our relationship that we both just automatically follow every day?"
    ]
};

io.on("connection", (socket) => {
    console.log("A user connected: " + socket.id);

    socket.on("join_room", (data) => {
        const roomName = data.roomName;
        const password = data.password;
        const targetRoom = rooms[roomName];

        if (targetRoom) {
            if (targetRoom.password === password) {
                if (targetRoom.users.length < 2) {
                    const position = targetRoom.users.length === 0 ? "left" : "right";
                    targetRoom.users.push(socket.id);
                    
                    socket.join(roomName);
                    
                    socket.emit("room_joined", { 
                        "status": "success", 
                        "roomName": roomName, 
                        "position": position,
                        "assets": targetRoom.assets
                    });

                    if (targetRoom.users.length === 2) {
                        io.to(roomName).emit("game_ready", "Both partners connected! Let the game begin.");
                        startTurn(roomName);
                    }
                } else {
                    socket.emit("room_error", "This room is already full.");
                }
            } else {
                socket.emit("room_error", "Incorrect password for " + roomName + " room.");
            }
        }
    });

    function startTurn(roomName) {
        const targetRoom = rooms[roomName];
        const activePlayerId = targetRoom.users[targetRoom.turnIndex];
        io.to(roomName).emit("turn_update", { "activePlayer": activePlayerId });
    }

    socket.on("select_category", (data) => {
        const category = data.category;
        const roomName = data.roomName;
        let categoryQuestions = [];
    
        // Logic for the Mix category
        if (category === "Mix") {
            for (let key in questionBank) {
                categoryQuestions = categoryQuestions.concat(questionBank[key]);
            }
        } else {
            // Standard category selection
            categoryQuestions = questionBank[category];
        }
        
        if (categoryQuestions && categoryQuestions.length > 0) {
            const randomIndex = Math.floor(Math.random() * categoryQuestions.length);
            const randomQuestion = categoryQuestions[randomIndex];
            
            io.to(roomName).emit("new_question", { "question": randomQuestion, "category": category });
        }
    });

    socket.on("submit_answer", (data) => {
        const roomName = data.roomName;
        io.to(roomName).emit("receive_answer", { "answer": data.answer, "sender": socket.id });
    });

    // New event to manually switch turns
    socket.on("next_turn", (data) => {
        const roomName = data.roomName;
        const targetRoom = rooms[roomName];
        
        targetRoom.turnIndex = targetRoom.turnIndex === 0 ? 1 : 0;
        startTurn(roomName);
    });

    // New event for the persistent side chat
    socket.on("send_side_chat", (data) => {
        io.to(data.roomName).emit("receive_side_chat", { "message": data.message, "sender": socket.id });
    });

    // Helper function to remove a user from the room data
    function handleUserLeave(socketId) {
        for (const roomName in rooms) {
            const room = rooms[roomName];
            const userIndex = room.users.indexOf(socketId);
            
            if (userIndex !== -1) {
                // Remove the user from the array so the room isn't "full" anymore
                room.users.splice(userIndex, 1);
                console.log("Removed user from room: " + roomName);
                
                // Alert the remaining partner
                io.to(roomName).emit("receive_side_chat", { 
                    "message": "System: Partner has left the room or disconnected.", 
                    "sender": "system" 
                });
            }
        }
    }

    // New event: Listens for the manual "Leave Room" button click
    socket.on("leave_room", () => {
        handleUserLeave(socket.id);
        
        // Officially remove their connection from the specific Socket.IO room
        for (const roomName in rooms) {
            socket.leave(roomName);
        }
    });

    // Updated event: Handles tab closures or lost connections
    socket.on("disconnect", () => {
        console.log("User disconnected: " + socket.id);
        handleUserLeave(socket.id);
    });
});

server.listen(3000, () => {
    console.log("Server is running on http://localhost:3000");
});
